<a href="https://colab.research.google.com/github/ThitipornJaiaue/python_dataviz2023/blob/main/Pandas101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd

## Meta data = Data that describtion data

ใช้อธิบายช้อมูล

## CSV = Comma Separated Values
ในการจะใส่ค่าแต่ละค่า จะใช้  comma ในการแย่ง

.csv = Comma Separated Values

data.go.th

# นำ Data เข้า
- upload to colab  # กรณีใช้เเค่ครั้งเดียว
- link with google drive

## upload to colab

In [70]:
data0 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/csv (1).csv')

In [71]:
#data0

In [72]:
data0.head()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

## link with google drive

In [68]:
from google.colab import drive
drive.mount('/content/drive')  # mount =  เชื่อมไดร์ฟ

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [73]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/csv (1).csv')
data1.head()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

In [74]:
data1.head(10)  # ดูหัวตาราง จากแถวบน 10 แถวแรก นับจาก 0-9

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
6,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,225400
7,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,452500
8,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,447000
9,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,497000

In [75]:
data1.tail(10) # ดูท้ายตาราง จากข้างล่าง

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
682,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางไทยเอราวัณ,3494000
683,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองหนึ่งตะวันตก,4330000
684,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองสองตะวันตก,9832000
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [76]:
data1.shape # ดูขนาด กี่เเถวกี่หลัก

(692, 9)

In [77]:
data1.describe()

         Issue_No  Fiscal_year  Department_code  Approved_buget
count  692.000000   692.000000     6.920000e+02    6.920000e+02
mean     0.333815    64.543353     4.534202e+07    1.482811e+06
std      0.474972     1.476149     1.303279e+07    2.464625e+06
min      0.000000    62.000000     1.100000e+07    0.000000e+00
25%      0.000000    63.000000     5.013000e+07    4.100000e+05
50%      0.000000    65.000000     5.023000e+07    5.980000e+05
75%      1.000000    66.000000     5.036000e+07    1.628250e+06
max      2.000000    66.000000     5.050000e+07    2.850000e+07

NaN = Not a Number

-------load data into pandas---24july23--------

DF คือ DataFlame เป็นชื่อ Data tructure ที่ Pandas ใช้

# ชี้ค่าในตาราง (indexing)

## มุมมองตาราง df[columns][rows]

In [78]:
data1['Budget_resource']

0        งบประจำปี
1        งบประจำปี
2        งบประจำปี
3        งบประจำปี
4        งบประจำปี
          ...
687    งบเพิ่มเติม
688    งบเพิ่มเติม
689    งบเพิ่มเติม
690    งบเพิ่มเติม
691    งบเพิ่มเติม
Name: Budget_resource, Length: 692, dtype: object

In [79]:
data1['Budget_resource'][690]

'งบเพิ่มเติม'

In [80]:
data1['Budget_resource'][-3:-1]

689    งบเพิ่มเติม
690    งบเพิ่มเติม
Name: Budget_resource, dtype: object

In [84]:
data1.columns

Index(['Budget_resource', 'Issue_No', 'Fiscal_year', 'Department_code',
       'Department', 'Core_budget_code', 'Expenditure_category', 'Item_name',
       'Approved_buget'],
      dtype='object')

In [83]:
data1[['Approved_buget','Item_name', 'Department']]

,Approved_buget,Item_name,Department
0,1193000,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,สำนักการระบายน้ำ
1,1100000,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,สำนักการระบายน้ำ
2,3075000,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,สำนักการระบายน้ำ
3,6240000,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,สำนักการระบายน้ำ
4,2685000,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,สำนักการระบายน้ำ
...,...,...,...
687,3686000,ขุดลอกคลองผักกะเฉด,สำนักงานเขตคลองสามวา
688,2575000,ขุดลอกคลองบึงทรายกองดิน,สำนักงานเขตคลองสามวา
689,689000,ขุดลอกลำรางซาฟารี,สำนักงานเขตคลองสามวา
690,464000,ขุดลอกลำรางตาจันทร์,สำนักงานเขตคลองสามวา
691,7578000,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,สำนักงานเขตบางบอน

In [85]:
data1[['Approved_buget','Item_name', 'Department']][6:11]

,Approved_buget,Item_name,Department
6,225400,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,สำนักงานเขตมีนบุรี
7,452500,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,สำนักงานเขตมีนบุรี
8,447000,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,สำนักงานเขตหนองจอก
9,497000,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,สำนักงานเขตหนองจอก
10,189500,ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50,สำนักงานเขตภาษีเจริญ

## มุมมองแบบ Array

In [86]:
 data1.iloc[0, 0] # .iloc เปลี่ยนมุมมองเป็น np.arry  ชี้เป็นเเถว คอลัม ติดลบ สไลด์ได้

'งบประจำปี'

In [87]:
 data1.iloc[-6,5]

nan

In [88]:
data1.tail(7)

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

# Table Slicing
ไม่ค่อยมีประสิทธิภาพ
ต้องทราบพิกัด

In [89]:
data1.iloc[-20 :,7:10]

                                             Item_name  Approved_buget
672  ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...          472000
673  ขุดลอกลำกระโดงแยกคลองบางขี้แก้ง (หมู่บ้านเอเวอ...          492000
674                         ขุดลอกคลองแยกคลองตาเทียม 1          469000
675  ขุดลอกลำกระโดงระหว่างซอยเพชรเกษม 43 กับ ซอยเพช...          493000
676                          ขุดลอกคลองแยกคลองยายเพิ่ม          481000
677                    ขุดลอกลำกระโดงข้างหมู่บ้านวรนุช          492000
678                                    ขุดลอกคลองตาตี่          483000
679                        ขุดลอกลำกระโดงข้างเดอะมอลล์          462000
680                      ขุดลอกลำกระโดงข้างบ้านบางแค 2          499000
681                                   ขุดลอกลำรางตาเชย         3559000
682                              ขุดลอกลำรางไทยเอราวัณ         3494000
683                             ขุดลอกคลองหนึ่งตะวันตก         4330000
684                               ขุดลอกคลองสองตะวันตก         9832000
685                                   ขุดลอกคลองกีบหมู         2925000
686                                 ขุดลอกคลองลำกะโหลก         3875000
687                                 ขุดลอกคลองผักกะเฉด         3686000
688                            ขุดลอกคลองบึงทรายกองดิน         2575000
689                                  ขุดลอกลำรางซาฟารี          689000
690                                ขุดลอกลำรางตาจันทร์          464000
691          ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล         7578000

 ## table Query

#### อยากได้รายการที่ได้รับอนุมัติงบเกิน 1 ล้านบาท
```df[logics]``` โดยที่ logics จะต้องมีจำนวนสมาชิกเท่ากับจำนวนแถวของ df

In [90]:
small_df = data1.iloc[-5:,:]
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [91]:
small_df[[False, True, True, False, False]]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000

## ปั้น List of Logics จากตาราง Pandas

In [92]:
small_df['Approved_buget']< 1000000

687    False
688    False
689     True
690     True
691    False
Name: Approved_buget, dtype: bool

In [93]:
small_df[small_df['Approved_buget']< 1000000]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

#### Quiz3 อยากได้รายการที่ได้รับอนุมัติงบมากกว่า 1 ล้านบาท แต่ไม่เกิน 2 ล้านบาท

In [94]:
data1[(data1['Approved_buget']> 1000000) & (data1['Approved_buget'] <= 2000000)]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
22,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง,1508000
25,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...,1975000
...,...,...,...,...,...,...,...,...,...
660,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองสะพานยาว,1756000
662,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองบางรักและคูน้ำซอยจรัญสนิทวงศ์ 89,1859000
665,งบเพิ่มเติม,1,66,50350000,สำนักงานเขตบางพลัด,NaN,งบลงทุน,ขุดลอกคลองวัดน้อยนางหงษ์,1187000
666,งบเพิ่มเติม,1,66,50360000,สำนักงานเขตจอมทอง,NaN,งบลงทุน,"ขุดลอกคลองลัดบางสะแก (1),(2) จากคลองบางค้อและค...",1581000
670,งบเพิ่มเติม,1,66,50360000,สำนักงานเขตจอมทอง,NaN,งบลงทุน,"ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร (3),...",1388000

In [95]:
small_df[(small_df['Approved_buget']> 1000000) & (small_df['Approved_buget'] <= 2000000)]

Empty DataFrame
Columns: [Budget_resource, Issue_No, Fiscal_year, Department_code, Department, Core_budget_code, Expenditure_category, Item_name, Approved_buget]
Index: []

In [ ]:
data1[data1['propertytype_name_en']== 'condo'] #ใช้ logi

KeyError: ignored

In [ ]:
data1['propertytype_name_en']== 'condo'

KeyError: ignored

In [ ]:
data1[data1['price_min'] > 10000000]

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
11,2452,unittype_8521,project_2906,New Villa Valdivia,1,Detached House,บ้าน,NaN,441.0,36900000.0,...,1.0,1.0,1.0,1.0,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:47,baania,https://baania.com/th/project/แกรนด์-บางกอก-บู...
31,17879,5f682d5d0499a4001b30c305,5f6472855bdc5300198eb80a,2BR Duplex,2,Condo,คอนโด,NaN,293.0,34222500.0,...,NaN,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:26:37,2020-12-25 11:27:21,baania,https://baania.com/th/project/ไบรท์-ภูเก็ต-5f6...
35,6309,unittype_3461,project_754,Type C,1,Detached House,บ้าน,NaN,390.0,11000000.0,...,NaN,1.0,1.0,NaN,NaN,NaN,2020-12-04 10:44:19,2020-10-14 21:21:23,baania,https://baania.com/th/project/บ้านล้านนาธารา-เ...
37,26913,unittype_23137,project_9231,4 Bedroom,2,Condo,คอนโด,NaN,305.0,24000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:59,2020-10-14 01:08:28,baania,https://baania.com/th/project/บางกอก-การ์เด้น-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42576,35213,unittype_22962,project_8609,Manhattan,1,Detached House,บ้าน,NaN,465.0,28900000.0,...,NaN,2.0,2.0,1.0,NaN,NaN,2021-11-12 13:33:58,2021-10-03 15:21:58,baania,https://baania.com/th/project/เดอะ-เจนทริ-สุขุ...
42606,24384,unittype_14126,project_5602,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,349.0,18000000.0,...,1.0,2.0,NaN,NaN,NaN,NaN,2020-12-04 10:45:58,2020-10-14 22:59:34,baania,https://baania.com/th/project/เดอะ-ซีนีธ-5602/...
42607,13546,unittype_40152,project_17505,2 Bedroom,2,Condo,คอนโด,NaN,71.0,17000000.0,...,NaN,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:23:03,2020-10-14 20:30:43,baania,https://baania.com/th/project/เดอะ-ไลน์-สาทร-1...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,130.0,36500000.0,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...

In [ ]:
data1[data1['price_min'] > 10000000].describe()

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,3481.000000,3481.000000,304.000000,3354.000000,3.481000e+03,138.000000,0.0,2149.000000,1784.000000,3420.000000,3411.000000,1570.000000,1236.000000,1897.000000,1396.000000,989.000000,497.000000,83.000000
mean,21066.205401,215.859523,52.622796,286.948606,2.577675e+07,4.536232,NaN,2.346208,2.867152,3.687427,3.357666,1.007006,1.046926,1.061676,1.169054,1.070779,1.108652,1.120482
std,12478.117102,2035.944151,31.406177,185.081647,2.789259e+07,2.015123,NaN,0.816617,1.284865,1.458689,1.101538,0.083437,0.222751,0.247118,0.473001,0.275603,0.411853,0.424769
min,1.000000,1.000000,1.000000,30.000000,1.003000e+07,1.000000,NaN,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,9796.000000,1.000000,30.000000,155.000000,1.300000e+07,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21525.000000,1.000000,51.400000,265.000000,1.700000e+07,4.000000,NaN,2.000000,3.000000,4.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,32420.000000,2.000000,72.625000,362.750000,2.790200e+07,5.750000,NaN,3.000000,3.000000,5.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,42620.000000,20000.000000,335.000000,2548.000000,5.800000e+08,10.000000,NaN,7.000000,10.000000,10.000000,10.000000,2.000000,3.000000,3.000000,5.000000,4.000000,4.000000,4.000000

# Quiz 4
1. ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ร้านบาท
2. พื้นที่ และ จำนวนห้องนอนของบ้านที่แพงที่สุด
3. จำนวนที่จอดรถและห้องน้ำของบ้านที่ถูกที่สุด
4. ชนิดของบ้านที่แพงที่สุด
5. บ้านชนิดไหนมีปริมาณมากที่สุด

In [ ]:
# 1. ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ร้านบาท
data1[(data1['price_min'] >=3000000) & (data1['price_min']<=5000000)].describe()
# Ans 3.928111e+06	 = 3.928111  ล้านบาท

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,8943.000000,8943.000000,1066.000000,8148.000000,8.943000e+03,418.000000,0.0,6917.000000,5602.000000,8749.000000,8604.000000,3290.00000,3239.000000,4791.000000,1963.000000,150.000000,1223.000000,161.000000
mean,21153.925976,1285.383987,46.709559,138.785306,3.922594e+06,2.653110,NaN,2.132716,1.877722,2.406904,2.736634,1.00152,1.005557,1.016489,1.028018,1.033333,1.038430,1.105590
std,12338.077057,4901.447720,18.555223,66.760066,5.847665e+05,1.128124,NaN,0.577204,0.497313,0.915960,0.986672,0.03896,0.074351,0.127361,0.171131,0.214153,0.200641,0.396902
min,2.000000,1.000000,2.000000,20.100000,3.000000e+06,1.000000,NaN,0.000000,1.000000,0.000000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,10042.500000,1.000000,30.000000,96.000000,3.450000e+06,2.000000,NaN,2.000000,2.000000,2.000000,2.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21864.000000,2.000000,50.000000,145.000000,3.880000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,32198.000000,3.000000,60.000000,178.000000,4.400000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,42617.000000,20000.000000,99.000000,896.000000,5.000000e+06,7.000000,NaN,4.000000,10.000000,9.000000,10.000000,2.00000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000

In [ ]:
price_mean = data1[(data1['price_min'] >=3000000) & (data1['price_min']<=5000000)]['price_min'].mean()

In [ ]:
print(f'ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ล้านบาท คือ {int(price_mean):,}')

ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ล้านบาท คือ 3,922,594

In [ ]:
#2.พื้นที่และจำนวนห้องนอนของบ้านที่แพงที่สุด
data1['price_min'].max()

580000000.0

In [ ]:
data1[data1['price_min']==580000000][['area_usable_min','count_room_bed']]

       area_usable_min  count_room_bed
33122           1182.0             3.0

In [ ]:
data1[data1['price_min']==data1['price_min'].max()][['area_usable_min','count_room_bed','price_min']]

       area_usable_min  count_room_bed    price_min
33122           1182.0             3.0  580000000.0

In [ ]:
data1[data1['price_min']==data1['price_min'].max()]

In [ ]:
#3.จำนวนที่จอดรถและห้องน้ำที่ถูกที่สุด
data1['price_min'].min()

100000.0

In [ ]:
data1[data1['price_min']==100000][['count_parking','count_room_bath']]

       count_parking  count_room_bath
8640             NaN              1.0
11019            NaN              1.0
17941            NaN              1.0
30364            NaN              1.0

In [ ]:
data1[data1['price_min']==data1['price_min'].min()][['propertytype_name_en','count_parking','count_room_bath','price_min']]

      propertytype_name_en  count_parking  count_room_bath  price_min
8640                 Condo            NaN              1.0   100000.0
11019                Condo            NaN              1.0   100000.0
17941                Condo            NaN              1.0   100000.0
30364                Condo            NaN              1.0   100000.0

In [ ]:
# 4. ชนิดของบ้านที่แพงที่สุด
data1.describe()
data1[data1['price_min'] == 580000000]
# Ans Condo

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
33122,8629,unittype_37324,project_16305,Penthouse,2,Condo,คอนโด,NaN,1182.0,580000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:31,2020-10-14 00:55:50,baania,https://baania.com/th/project/เดอะ-สุโขทัย-เรส...

In [ ]:
# 4. ชนิดของบ้านที่แพงที่สุด
data1['propertytype_name_en'][data1['price_min'] == 580000000]

33122    Condo
Name: propertytype_name_en, dtype: object

In [ ]:
data1[data1['price_min']==data1['price_min'].max()][['propertytype_name_en','price_min']]

      propertytype_name_en    price_min
33122                Condo  580000000.0

In [ ]:
#5. บ้านชนิดไหนมีปริมาณมากที่สุด
data1['propertytype_name_en'].describe()

count              42625
unique                11
top       Detached House
freq               17670
Name: propertytype_name_en, dtype: object

In [ ]:
import os

In [ ]:
path = '/content/drive/My Drive/dataviz_2021_data'

In [ ]:
covid_file_path = os.path.join(path,'pm-20-jan-2021.csv')
print(covid_file_path)

/content/drive/My Drive/dataviz_2021_data/pm-20-jan-2021.csv

In [ ]:
a = path + '/pm-18-jan-2021.csv'
print(a)

/content/drive/My Drive/dataviz_2021_data/pm-18-jan-2021.csv

## load data to memory

In [ ]:
data_covid = pd.read_csv(covid_file_path)
data_covid

         No.  ...                                         risk
0          1  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
1          2  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
2          3  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
3          4  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
4          5  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...  ...                                          ...
12648  12649  ...                             State Quarantine
12649  12650  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12650  12651  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651  12652  ...                                Cluster ระยอง
12652  12653  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[12653 rows x 10 columns]

In [ ]:
data_covid.head()

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

NaN = Not a Number

In [ ]:
data_covid.head(20)

    No.  ...                                               risk
0     1  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
1     2  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
2     3  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
3     4  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
4     5  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
5     6  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
6     7  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
7     8  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
8     9  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
9    10  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
10   11  ...        สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11   12  ...        สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12   13  ...        สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
13   14  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
14   15  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
15   16  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...
16   17  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
17   18  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
18   19  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
19   20  ...                      คนไทยเดินทางกลับจากต่างประเทศ

[20 rows x 10 columns]

In [ ]:
data_covid.tail()

         No.  ...                                         risk
12648  12649  ...                             State Quarantine
12649  12650  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12650  12651  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651  12652  ...                                Cluster ระยอง
12652  12653  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[5 rows x 10 columns]

In [ ]:
data_covid.shape

(12653, 10)

## ชี้ค่าในตาราง

#### basic

In [ ]:
data_covid['province_of_onset']

0        กรุงเทพมหานคร
1        กรุงเทพมหานคร
2               นครปฐม
3        กรุงเทพมหานคร
4        กรุงเทพมหานคร
             ...
12648           ชลบุรี
12649            ระยอง
12650            ระยอง
12651            ระยอง
12652              ตาก
Name: province_of_onset, Length: 12653, dtype: object

In [ ]:
data_covid['risk'][12649]

'สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้'

#### .iloc

In [ ]:
data_covid.iloc[4,7]

'กรุงเทพมหานคร'

# เรียนถึงนี่ 12 Jan 2022

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [ ]:
smaller_table = data_covid[['province_of_onset','announce_date','risk']]
smaller_table

      province_of_onset  ...                                         risk
0         กรุงเทพมหานคร  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
1         กรุงเทพมหานคร  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
2                นครปฐม  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
3         กรุงเทพมหานคร  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
4         กรุงเทพมหานคร  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
...                 ...  ...                                          ...
12648            ชลบุรี  ...                             State Quarantine
12649             ระยอง  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12650             ระยอง  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651             ระยอง  ...                                Cluster ระยอง
12652               ตาก  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[12653 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [ ]:
data_covid.iloc[1:5,:]

   No. announce_date  ... district_of_onset                              risk
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 10 columns]

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

```pddf```[list_of_logical_values] คือการเลือก row ที่ logical values เป็น True

In [ ]:
data_covid['province_of_onset']

0        กรุงเทพมหานคร
1        กรุงเทพมหานคร
2               นครปฐม
3        กรุงเทพมหานคร
4        กรุงเทพมหานคร
             ...
12648           ชลบุรี
12649            ระยอง
12650            ระยอง
12651            ระยอง
12652              ตาก
Name: province_of_onset, Length: 12653, dtype: object

In [ ]:
data_covid['province_of_onset']=='ขอนแก่น'

0        False
1        False
2        False
3        False
4        False
         ...
12648    False
12649    False
12650    False
12651    False
12652    False
Name: province_of_onset, Length: 12653, dtype: bool

In [ ]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

         No.  ...                                           risk
180      181  ...                                        สนามมวย
462      463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466    1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970    1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637    2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ
2673    2674  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
5948    5949  ...                              Cluster สมุทรสาคร
6082    6083  ...                              Cluster สมุทรสาคร
9333    9334  ...                           อยู่ระหว่างการสอบสวน
9334    9335  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610  10611  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517  11518  ...                           อยู่ระหว่างการสอบสวน
11697  11698  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698  11699  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[14 rows x 10 columns]

In [ ]:
data_covid[data_covid['age']>=70]

         No.  ...                                               risk
1          2  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
2          3  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
7          8  ...                   คนต่างชาติเดินทางมาจากต่างประเทศ
24        25  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...
82        83  ...                                            สนามมวย
...      ...  ...                                                ...
11694  11695  ...      ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
11700  11701  ...        สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11730  11731  ...                                  Cluster สมุทรสาคร
11741  11742  ...                               อยู่ระหว่างการสอบสวน
12102  12103  ...                                  Cluster สมุทรสาคร

[245 rows x 10 columns]

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [ ]:
eight_rows_covid = data_covid.iloc[:8,3:] # ตารางตัวอย่าง
eight_rows_covid

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1  หญิง  74.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2  หญิง  73.0  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4  หญิง  66.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6  หญิง  57.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
7  หญิง  73.0  ...            หัวหิน  คนต่างชาติเดินทางมาจากต่างประเทศ

[8 rows x 7 columns]

In [ ]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ list ที่ มีค่า logic ของ แต่ละ row โดยที่ ค่า True คือ เลือก ค่า False คือไม่เลืิอก

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2  หญิง  73.0  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 7 columns]

In [ ]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [ ]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

    sex   age  ... district_of_onset                              risk
0  หญิง  61.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1  หญิง  74.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
3   ชาย  68.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4  หญิง  66.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5  หญิง  33.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6  หญิง  57.0  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[6 rows x 7 columns]

In [ ]:
eight_rows_covid['district_of_onset'] == 'เมือง'

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: district_of_onset, dtype: bool

In [ ]:
import numpy as np

$.isnull()$ ใช้ตรวจสอบว่าเป็น NaN หรือไม่

In [ ]:
eight_rows_covid['district_of_onset'].isnull()

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: district_of_onset, dtype: bool

In [ ]:
sum(eight_rows_covid['district_of_onset'].isnull())

6

Quiz (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของ**ผู้ชาย** ในข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของ**ผู้ชาย** ในจังหวัดขอนแก่น
3.   หาจำนวนผู้ป่วยที่เป็นคน **ที่ไม่ใช่คนไทย**

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[12653 rows x 3 columns]

In [ ]:
female = this_data[this_data['sex']=='หญิง']
female

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
4      หญิง  66.0     กรุงเทพมหานคร
5      หญิง  33.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[5332 rows x 3 columns]

In [ ]:
female['age']

0        61.0
1        74.0
2        73.0
4        66.0
5        33.0
         ...
12648    44.0
12649    52.0
12650    23.0
12651    29.0
12652    22.0
Name: age, Length: 5332, dtype: float64

In [ ]:
sum = 0
N = 0
for a in female['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 36.63955450022614

In [ ]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 41.57142857142857

In [ ]:
female[(female['province_of_onset']=='ขอนแก่น') | (female['province_of_onset']=='หนองคาย')]

        sex   age province_of_onset
462    หญิง  36.0           ขอนแก่น
1051   หญิง  30.0           หนองคาย
1970   หญิง  70.0           ขอนแก่น
2637   หญิง  63.0           ขอนแก่น
5948   หญิง  32.0           ขอนแก่น
6082   หญิง  36.0           ขอนแก่น
10834  หญิง  40.0           หนองคาย
11697  หญิง  17.0           ขอนแก่น
11698  หญิง  37.0           ขอนแก่น

#### หาจำนวนคนป่วยที่ไม่ใช่คนไทย

In [ ]:
import numpy as np

In [ ]:
np.sum(data_covid['nationality'].dropna() != 'Thailand')

4129

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [ ]:
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[12653 rows x 3 columns]

In [ ]:
this_data.shape #(12423, 3)

(12653, 3)

In [ ]:
this_data.dropna()

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[8478 rows x 3 columns]

In [ ]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(12653, 10)
(6655, 10)

In [ ]:
this_data.dropna(subset=['age','sex'])

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[8880 rows x 3 columns]

In [ ]:
print(this_data.dropna().shape)
print(this_data.dropna(subset=['sex','age']).shape)

(8478, 3)
(8880, 3)

# ตรวจสอบ Missing (```isnull()```)

In [ ]:
data1.isnull()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
687,False,False,False,False,False,True,False,False,False
688,False,False,False,False,False,True,False,False,False
689,False,False,False,False,False,True,False,False,False
690,False,False,False,False,False,True,False,False,False
691,False,False,False,False,False,True,False,False,False

In [ ]:
data1.isnull().any() # .any() เอาค่าความจริงใน column มา OR กัน (ใช้ในการหาค่าว่าง)

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code         True
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1.isnull().all() # .all() เอาค่าความจริงใน column มา AND กัน

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code        False
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1.isnull().any().any() #.any ตัวแรกสรุกคอลัมน์ของแต่ละคอลัมน์มาออลกัน

True

การจัดการ Missing Value

- ลบ record ที่เป็น missing (dropna)
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown (fillna)
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.) (fillna)

ไม่ควรจะลบ  data ออกไปเกิน 5 %

## NaN Not a Number
## Null Null
## NA Not Available/Not Authorised
## None

## Dropna

In [ ]:
data1.shape

(692, 9)

Pandas Dropna -> https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

In [ ]:
data1.dropna().shape

(266, 9)

In [ ]:
data1.dropna(subset=['Fiscal_year']).shape ## ถ้ามี Missing เติม dropna

(692, 9)

In [ ]:
data1.isnull(). any()

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code         True
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1_1 = data1.dropna(subset=['Fiscal_year']).shape

In [ ]:
data1_1.isnull(),any()

AttributeError: ignored

In [ ]:
data1.dropna(subset=['Fiscal_year'],inplace=True)

In [ ]:
data1.isnull().any()

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code         True
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

## FILLNA

In [ ]:
data1.fillna('-',inplace=True)

In [ ]:
set(data1['Core_budget_code'])

{'-',
 '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต'}

In [ ]:
data1.isnull().any()

Budget_resource         False
Issue_No                False
Fiscal_year             False
Department_code         False
Department              False
Core_budget_code        False
Expenditure_category    False
Item_name               False
Approved_buget          False
dtype: bool

In [ ]:
data1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,-,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

---End---

## HW3


1.   รายการที่แพงและถูกที่สุดคือรายการไหน
2.   รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'
3.   จากข้อ 2 เขตไหนใช้งบประมาณเยอะกว่ากัน
4.   Core Budget ไหน ('12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม', '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

In [96]:
data1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [97]:
## 1. รายการที่แพงและถูกที่สุดคือรายการไหน
data1['Approved_buget'].describe()
# max 2.850000e+07 = 28.5 ล้านบาท
# min 0.000000e+00 = 0 บาท

count    6.920000e+02
mean     1.482811e+06
std      2.464625e+06
min      0.000000e+00
25%      4.100000e+05
50%      5.980000e+05
75%      1.628250e+06
max      2.850000e+07
Name: Approved_buget, dtype: float64

In [98]:
data1['Approved_buget'].max() # max 2.850000e+07 = 28.5 ล้านบาท

28500000

In [99]:
data1[data1['Approved_buget']==28500000][['Item_name','Approved_buget']]

                                             Item_name  Approved_buget
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000

In [100]:
data1['Approved_buget'].min() # min 0.000000e+00 = 0 บาท

0

In [101]:
data1[data1['Approved_buget']==0][['Item_name','Approved_buget']]

                                             Item_name  Approved_buget
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

In [102]:
data1_1 = data1[['Item_name','Approved_buget']]

In [103]:
data1_HW3 = data1_1 [(data1_1['Approved_buget'] == data1_1['Approved_buget'].max()) | (data1_1['Approved_buget'] ==data1_1['Approved_buget'].min())]
data1_HW3

                                             Item_name  Approved_buget
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

In [104]:
## 2. รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'
data1[data1['Department']=='สำนักงานเขตคลองสาน']

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
57,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคูน้ำสารภี 1,513000
58,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองเพลง\n,2218000
59,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...,89000
122,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองธรรมชาติและคลองแยกคลองวัดทองธร...,500000
123,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองโรงปลา,90000
212,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงซอยอิสรภาพ 3,162000
213,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองหลังวัดพิชัยญาติและคลองวัดน้อยเก่า,209000
214,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองพระยาเกษม,487000
215,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองข้างโรงเรียนปทุมวิทยา,80000
271,งบประจำปี,0,65,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...,659000
441,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองโรงหนัง จากคลองบางไส้ไก่ถึงแม่น้ำเจ้...,1325000
442,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองข้างโรงน้ำแข็ง จากสุดระยะคลองถึงแม่น...,358000
443,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองข้างวัดอนงค์ จากคลองหลัง\nวัดพิชัยญา...,205000

In [105]:
data1[data1['Department']=='สำนักงานเขตคลองสามวา']

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
252,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...,6236000
253,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...,5815000
400,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางวัดแป้นทอง จากคลองสี่ตะวันตก ถึงคลอ...,1246200
401,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางครูพัว จากคลองสองตะวันตก ถึงคลองหนึ...,542200
402,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาชม จากคลองลำควายตาย ถึงคลองบางชัน,452300
403,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองเจ๊ก จากคลองหนึ่งตะวันตก ถึงสุดเขตคล...,1204500
404,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองซอยเชื่อมคลองลำแบนกับคลองหนองระแหง จ...,453600
681,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาเชย,3559000
682,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางไทยเอราวัณ,3494000
683,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองหนึ่งตะวันตก,4330000
684,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองสองตะวันตก,9832000
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

In [106]:
data1[(data1['Department']=='สำนักงานเขตคลองสาน') | (data1['Department']=='สำนักงานเขตคลองสามวา')]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
57,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคูน้ำสารภี 1,513000
58,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองเพลง\n,2218000
59,งบประจำปี,0,62,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...,89000
122,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองวัดทองธรรมชาติและคลองแยกคลองวัดทองธร...,500000
123,งบประจำปี,0,63,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองโรงปลา,90000
212,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกลำกระโดงซอยอิสรภาพ 3,162000
213,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองหลังวัดพิชัยญาติและคลองวัดน้อยเก่า,209000
214,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองพระยาเกษม,487000
215,งบประจำปี,0,64,50170000,สำนักงานเขตคลองสาน,-,งบลงทุน,ขุดลอกคลองข้างโรงเรียนปทุมวิทยา,80000
252,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...,6236000
253,งบประจำปี,0,64,50460000,สำนักงานเขตคลองสามวา,-,งบลงทุน,ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...,5815000
271,งบประจำปี,0,65,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...,659000
400,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางวัดแป้นทอง จากคลองสี่ตะวันตก ถึงคลอ...,1246200
401,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางครูพัว จากคลองสองตะวันตก ถึงคลองหนึ...,542200
402,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาชม จากคลองลำควายตาย ถึงคลองบางชัน,452300
403,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองเจ๊ก จากคลองหนึ่งตะวันตก ถึงสุดเขตคล...,1204500
404,งบเพิ่มเติม,1,65,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองซอยเชื่อมคลองลำแบนกับคลองหนองระแหง จ...,453600
441,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองโรงหนัง จากคลองบางไส้ไก่ถึงแม่น้ำเจ้...,1325000
442,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองข้างโรงน้ำแข็ง จากสุดระยะคลองถึงแม่น...,358000
443,งบประจำปี,0,66,50170000,สำนักงานเขตคลองสาน,NaN,งบลงทุน,ขุดลอกคลองข้างวัดอนงค์ จากคลองหลัง\nวัดพิชัยญา...,205000
681,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาเชย,3559000
682,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางไทยเอราวัณ,3494000
683,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองหนึ่งตะวันตก,4330000
684,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองสองตะวันตก,9832000
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

In [107]:
## 3. จากข้อ 2 เขตไหนใช้งบประมาณเยอะกว่ากัน
# compare = data1[(data1['Department'] == 'สำนักงานเขตคลองสาม') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

In [108]:
data1[data1['Department']=='สำนักงานเขตคลองสาน']['Approved_buget'] .sum()
print(f'สำนักงานเขตคลองสาน ใช้งบประมาณรวม เป็นเงิน',data1[data1['Department']=='สำนักงานเขตคลองสาน']['Approved_buget'] .sum(),f'บาท')

สำนักงานเขตคลองสาน ใช้งบประมาณรวม เป็นเงิน 6895000 บาท

In [109]:
data1[data1['Department']=='สำนักงานเขตคลองสามวา']['Approved_buget'] .sum()
print(f'สำนักงานเขตคลองสามวา ใช้งบประมาณรวม เป็นเงิน',data1[data1['Department']=='สำนักงานเขตคลองสามวา']['Approved_buget'] .sum(),f'บาท')

สำนักงานเขตคลองสามวา ใช้งบประมาณรวม เป็นเงิน 51378800 บาท

In [127]:
# Ans เขต สำนักงานเขตคลองสามวา ใช้งบประมาณเยอะกว่า สำนักงานเขตคลองสาน
print(f'เขต สำนักงานเขตคลองสามวา ใช้งบประมาณเยอะกว่า สำนักงานเขตคลองสาน โดยมีงบประมาณอยู่ที่', data1[data1['Department']=='สำนักงานเขตคลองสามวา']['Approved_buget'] .sum(), f'บาท' )

เขต สำนักงานเขตคลองสามวา ใช้งบประมาณเยอะกว่า สำนักงานเขตคลองสาน โดยมีงบประมาณอยู่ที่ 51378800 บาท

In [110]:
## 4. Core Budget ไหน ('12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม', '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
# '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด
set(data1['Core_budget_code'])

{'-',
 '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต',
 nan}

In [111]:
core_12 = data1[(data1['Core_budget_code'] == "12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม")]
core_12

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
6,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,225400
7,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,452500
10,งบประจำปี,0,62,50210000,สำนักงานเขตภาษีเจริญ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50,189500
11,งบประจำปี,0,62,50260000,สำนักงานเขตจตุจักร,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทุ่งจากซอยวิภาวดีรังสิต 36 ถึงคลองลา...,426000
13,งบประจำปี,0,62,50350000,สำนักงานเขตบางพลัด,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองวัดดาวดึงษาราม,258000
15,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างโรงเรียนคลองหนองใหญ่,210000
16,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างบริษัทประยูรวิศว์,486000
17,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...,454000
18,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างบ้านบางแค 2,410000
19,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองหลวงพ่อบ้านแหลม,442000
20,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองผู้ใหญ่เส็ง 1,347000
21,งบประจำปี,0,62,50400000,สำนักงานเขตบางแค,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำกระโดงข้างห้างเดอะมอลล์บางแค,482000
22,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง,1508000
23,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางแคจากถนนกาญจนาภิเษกถึงคลองพระยารา...,4370000
24,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางมดจากคลองสนามชัยถึงคลองสวน,6570000
25,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...,1975000
26,งบประจำปี,0,63,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองแจงร้อนจากแม่น้ำเจ้าพระยาถึงคลองขวาง,2580000
29,งบประจำปี,0,63,50220000,สำนักงานเขตหนองแขม,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองตาปลั่ง 1 จากคลองภาษีเจริญถึงคลองหนา...,4380000
30,งบประจำปี,0,63,50220000,สำนักงานเขตหนองแขม,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองตาปลั่ง 2 จากถนนบางบอน 5 ถึงสุดระยะท...,1626000
31,งบประจำปี,0,63,50250000,สำนักงานเขตดอนเมือง,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางสาธารณะเลียบหมู่บ้านบัณฑิตโฮมตั้งแต...,1256000
32,งบประจำปี,0,63,50250000,สำนักงานเขตดอนเมือง,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางข้างบริษัทไทยเทยิ่น ตั้งแต่ถนนวิภาว...,1117000

In [112]:
mean_core12 = core_12['Approved_buget'].mean()
mean_core12

1676459.2592592593

In [113]:
core_17 = data1[(data1['Core_budget_code'] == "17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร")]
core_17

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
27,งบประจำปี,0,63,50150000,สำนักงานเขตหนองจอก,17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพ...,งบลงทุน,ขุดลอกคลองลำไทรจากคลองลำปลาทิวถึงคลองลำตาจีน แ...,1850000
28,งบประจำปี,0,63,50150000,สำนักงานเขตหนองจอก,17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพ...,งบลงทุน,ขุดลอกคลองหกโรงจากคลองหนึ่งถึงคลองสอง แขวงกระท...,1825000

In [118]:
mean_core17 = core_17['Approved_buget'].mean()
mean_core17

1837500.0

In [121]:
core_28 = data1[(data1['Core_budget_code'] == "28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต")]
core_28

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
8,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,447000
9,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,497000
12,งบประจำปี,0,62,50320000,สำนักงานเขตราชเทวี,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองส้มป่อย จากบ่อสูบน้ำคลองส้มป่อยถึงคล...,561000
14,งบประจำปี,0,62,50370000,สำนักงานเขตดินแดง,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกลำรางศรีศุภราช จากถนนสุทธิสารวินิจฉัยถึง...,437000

In [122]:
mean_core28 = core_28['Approved_buget'].mean()
mean_core28

485500.0

In [125]:
# Ans ค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด
print(f'Core Budget ของ เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด โดยอยู่ที่ ', mean_core17, f'บาท' )

Core Budget ของ เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด โดยอยู่ที่  1837500.0 บาท

----เริ่ม คาบหน้า (27 july 2023)----

### การวนลูป record ในตาราง  (```.iterrows```)

In [129]:
for row_i in range(len(data1)):
  print(data1.iloc[row_i,:])
  print('-----------------')

Streaming output truncated to the last 5000 lines.
Core_budget_code                                          -
Expenditure_category                                งบลงทุน
Item_name               ขุดลอกคลองสาธารณะข้างหมู่บ้านเทพนคร
Approved_buget                                       495000
Name: 237, dtype: object
-----------------
Budget_resource                  งบประจำปี
Issue_No                                 0
Fiscal_year                             64
Department_code                   50400000
Department                สำนักงานเขตบางแค
Core_budget_code                         -
Expenditure_category               งบลงทุน
Item_name               ขุดลอกคลองยายเพิ่ม
Approved_buget                      439000
Name: 238, dtype: object
-----------------
Budget_resource                งบประจำปี
Issue_No                               0
Fiscal_year                           64
Department_code                 50400000
Department              สำนักงานเขตบางแค
Core_budget_code                       -
Expenditure_category             งบลงทุน
Item_name               ขุดลอกคลองยายกวย
Approved_buget                    485000
Name: 239, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50400000
Department               สำนักงานเขตบางแค
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name               ขุดลอกคลองเล้าหมู
Approved_buget                     492000
Name: 240, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50400000
Department                                               สำนักงานเขตบางแค
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกลำกระโดงข้างหมู่บ้านศรีมงคล (ตัดซอยยิ่งเ...
Approved_buget                                                     478000
Name: 241, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50400000
Department               สำนักงานเขตบางแค
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name               ขุดลอกคลองบางด้วน
Approved_buget                     497000
Name: 242, dtype: object
-----------------
Budget_resource                                       งบประจำปี
Issue_No                                                      0
Fiscal_year                                                  64
Department_code                                        50400000
Department                                     สำนักงานเขตบางแค
Core_budget_code                                              -
Expenditure_category                                    งบลงทุน
Item_name               ขุดลอกลำกระโดงในหมู่บ้านร่ำรวยนิเวศน์ 2
Approved_buget                                           334000
Name: 243, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50420000
Department                สำนักงานเขตสายไหม
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name               ขุดลอกคลองจรเข้โพรง
Approved_buget                      1325000
Name: 244, dtype: object
-----------------
Budget_resource                     งบประจำปี
Issue_No                                    0
Fiscal_year                                64
Department_code                      50420000
Department                  สำนักงานเขตสายไหม
Core_budget_code                            -
Expenditure_category                  งบลงทุน
Item_name               ขุดลอกคลองจ้าหล่าใหญ่
Approved_buget                        1751000
Name: 245, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50420000
Department              สำนักงานเขตสายไหม
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name               ขุดลอกคลองเต้าปูน
Approved_buget                     353000
Name: 246, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50430000
Department              สำนักงานเขตคันนายาว
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name                ขุดลอกลำรางชวดด้วน
Approved_buget                      1106600
Name: 247, dtype: object
-----------------
Budget_resource                               งบประจำปี
Issue_No                                              0
Fiscal_year                                          64
Department_code                                50430000
Department                          สำนักงานเขตคันนายาว
Core_budget_code                                      -
Expenditure_category                            งบลงทุน
Item_name               ขุดลอกลำรางข้างโรงเรียนคันนายาว
Approved_buget                                   294000
Name: 248, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50430000
Department              สำนักงานเขตคันนายาว
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name               ขุดลอกลำรางยายเลิ้ง
Approved_buget                       291000
Name: 249, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50440000
Department              สำนักงานเขตสะพานสูง
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name               ขุดลอกคลองสะพานสูง
Approved_buget                      1601000
Name: 250, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50440000
Department              สำนักงานเขตสะพานสูง
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name                ขุดลอกคลองบัวคลี่
Approved_buget                      3961000
Name: 251, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50460000
Department                                           สำนักงานเขตคลองสามวา
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...
Approved_buget                                                    6236000
Name: 252, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50460000
Department                                           สำนักงานเขตคลองสามวา
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...
Approved_buget                                                    5815000
Name: 253, dtype: object
-----------------
Budget_resource                   งบประจำปี
Issue_No                                  0
Fiscal_year                              64
Department_code                    50490000
Department               สำนักงานเขตทุ่งครุ
Core_budget_code                          -
Expenditure_category                งบลงทุน
Item_name               ขุดลอกคลองสะพานควาย
Approved_buget                      2207000
Name: 254, dtype: object
-----------------
Budget_resource                    งบประจำปี
Issue_No                                   0
Fiscal_year                               64
Department_code                     50500000
Department                 สำนักงานเขตบางบอน
Core_budget_code                           -
Expenditure_category                 งบลงทุน
Item_name               ขุดลอกคลองรางขวาง 1
Approved_buget                        498000
Name: 255, dtype: object
-----------------
Budget_resource                    งบประจำปี
Issue_No                                   0
Fiscal_year                               64
Department_code                     50500000
Department                 สำนักงานเขตบางบอน
Core_budget_code                           -
Expenditure_category                 งบลงทุน
Item_name               ขุดลอกคลองรางขวาง 2
Approved_buget                        494000
Name: 256, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50500000
Department              สำนักงานเขตบางบอน
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name                ขุดลอกลำรางข่อย
Approved_buget                     471000
Name: 257, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50500000
Department                                              สำนักงานเขตบางบอน
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกลำรางซอยเอกชัย 45 จากคลองบางบอน ถึงบ้านเ...
Approved_buget                                                     474000
Name: 258, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50500000
Department                                              สำนักงานเขตบางบอน
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกลำรางซอยเอกชัย 89 จากคลองบางบอน ถึงสุดเข...
Approved_buget                                                     342000
Name: 259, dtype: object
-----------------
Budget_resource                                    งบประจำปี
Issue_No                                                   0
Fiscal_year                                               64
Department_code                                     50500000
Department                                 สำนักงานเขตบางบอน
Core_budget_code                                           -
Expenditure_category                                 งบลงทุน
Item_name               ขุดลอกลำกระโดงข้างซอยเอกชัย 43 แยก 2
Approved_buget                                        472000
Name: 260, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50500000
Department              สำนักงานเขตบางบอน
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name                ขุดลอกคลองนายผล
Approved_buget                     488000
Name: 261, dtype: object
-----------------
Budget_resource                  งบประจำปี
Issue_No                                 0
Fiscal_year                             64
Department_code                   50500000
Department               สำนักงานเขตบางบอน
Core_budget_code                         -
Expenditure_category               งบลงทุน
Item_name               ขุดลอกคลองบางด้วน
Approved_buget                      410000
Name: 262, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            64
Department_code                                                  50500000
Department                                              สำนักงานเขตบางบอน
Core_budget_code                                                        -
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองเนตรนุสรณ์ จากคลองบางบอนถึงสุดเขตกรุ...
Approved_buget                                                     978000
Name: 263, dtype: object
-----------------
Budget_resource                 งบประจำปี
Issue_No                                0
Fiscal_year                            64
Department_code                  50500000
Department              สำนักงานเขตบางบอน
Core_budget_code                        -
Expenditure_category              งบลงทุน
Item_name                 ขุดลอกคลองควาย
Approved_buget                     498000
Name: 264, dtype: object
-----------------
Budget_resource                    งบประจำปี
Issue_No                                   0
Fiscal_year                               64
Department_code                     50500000
Department                 สำนักงานเขตบางบอน
Core_budget_code                           -
Expenditure_category                 งบลงทุน
Item_name               ขุดลอกคลองโคกกะวะดี
Approved_buget                        486000
Name: 265, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  11000000
Department                                               สำนักการระบายน้ำ
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองบางมะเขือ \r\nจากสถานีสูบน้ำคลองบางม...
Approved_buget                                                    1264000
Name: 266, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  11000000
Department                                               สำนักการระบายน้ำ
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคูน้ำข้างโรงพยาบาลบำรุงราษฎร์\r\nจากคลอง...
Approved_buget                                                    1316000
Name: 267, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  50090000
Department                                            สำนักงานเขตห้วยขวาง
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกลำรางแยกคลองบางซื่อ จากคลองบางซื่อถึงหลั...
Approved_buget                                                     341000
Name: 268, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  50120000
Department                                              สำนักงานเขตบางเขน
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองกะเฉด จากซอยรามอินทรา 39 แยก 28 ถึงซ...
Approved_buget                                                     730000
Name: 269, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  50130000
Department                                             สำนักงานเขตมีนบุรี
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกลำรางแยกคลองลำนายโส ตั้งแต่ถนนบัวขาวฝั่ง...
Approved_buget                                                     488000
Name: 270, dtype: object
-----------------
Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            65
Department_code                                                  50170000
Department                                             สำนักงานเขตคลองสาน
Core_budget_code                                                      NaN
Expenditure_category                                              งบลงทุน
Item_name               ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...
Approved_buget                                                     659000
Name: 271, dtype: object
-----------------
Budget_resource                                              งบประจำปี
Issue_No                                                             0
Fiscal_year                                                         65
Department_code                                               50180000
Department                                       สำนักงานเขตบางกอกใหญ่
Core_budget_code                                                   NaN
Expenditure_category                                           งบลงทุน
Item_name               ขุดลอกคลองวัดหนัง จากคลองวัดดีดวกถึงสุดเขตคลอง
Approved_buget                                                  422300
Name: 272, dtype: object
-----------------
Budget_resource                                                งบประจำปี
Issue_No                                                               0
Fiscal_year                                                           65
Department_code                                                 50180000
Department                                         สำนักงานเขตบางกอกใหญ่
Core_budget_code                                                     NaN

In [134]:
for row in data1.iterrows():
  #print(row)
  print(row[1]['Fiscal_year'])
  print('--------------')

62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
62
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
63
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
64
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
65
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------
66
--------------

วนลูป ช่วยในการสร้าง data เพิ่ม

##การสร้าง columns เพิ่ม
```df['ชื่อ column ใหม่'] = list of data # list of data มีจำนวนสมาชิกเท่ากับจำนวน row1 ของตาราง```

In [135]:
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [137]:
small_df['ผู้รับผิดชอบ'] = ['ลุงตู่', 'ลุงตู่', 'ลุงป้อม', 'ชัชชาติ', 'พิธา']

<ipython-input-137-dd668cf87aac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_df['ผู้รับผิดชอบ'] = ['ลุงตู่', 'ลุงตู่', 'ลุงป้อม', 'ชัชชาติ', 'พิธา']

In [145]:
#small_df

##การลบ columns

In [139]:
small_df.drop(axis=1,columns=['Core_budget_code']) ##axis คือ แกน drop axis แกน1 ##ไม่ใส่ได้ แต่มีค่า defalt

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Expenditure_category,Item_name,Approved_buget,ผู้รับผิดชอบ
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000,ลุงตู่
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000,ลุงตู่
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางซาฟารี,689000,ลุงป้อม
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000,ชัชชาติ
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000,พิธา

In [141]:
#small_df.drop()

In [143]:
#สร้าง column ใหม่ ที่นำสาม column มารวมกัน
new_column = list()
for row in data1.iterrows():
  new_col = f"{row[1]['Department']}-{row[1]['Expenditure_category']}-{row[1]['Item_name']}"
  new_column.append(new_col)

In [146]:
#new_column

In [147]:
data1['describtion'] = new_column
data1 = data1.drop(axis=1, columns=['Department', 'Expenditure_category', 'Item_name'])

In [148]:
data1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Core_budget_code,Approved_buget,describtion
0,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,1193000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองบางกะปิจากค...
1,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,1100000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองทรงกระเทียม...
2,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,3075000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองเป้งจากคลอง...
3,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,6240000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกคลองลำพังพวยจาก...
4,งบประจำปี,0,62,11000000,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,2685000,สำนักการระบายน้ำ-งบลงทุน-ขุดลอกบึงรางเข้จากคลอ...
...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,NaN,3686000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกคลองผักกะเฉด
688,งบเพิ่มเติม,1,66,50460000,NaN,2575000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกคลองบึงทราย...
689,งบเพิ่มเติม,1,66,50460000,NaN,689000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกลำรางซาฟารี
690,งบเพิ่มเติม,1,66,50460000,NaN,464000,สำนักงานเขตคลองสามวา-งบลงทุน-ขุดลอกลำรางตาจันทร์
691,งบเพิ่มเติม,1,66,50500000,NaN,7578000,สำนักงานเขตบางบอน-งบลงทุน-ขุดลอกคลองบางบอนต่อจ...

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[12653 rows x 3 columns]

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    # print(each_row[1]['sex'])
    if (each_row[1]['age'] <= 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(1466, sex                      ชาย
age                       19
province_of_onset    ขอนแก่น
Name: 1466, dtype: object)
(9333, sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 9333, dtype: object)
(9334, sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object)
(10610, sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 10610, dtype: object)
(11517, sex                      ชาย
age                       12
province_of_onset    ขอนแก่น
Name: 11517, dtype: object)
(11697, sex                     หญิง
age                       17
province_of_onset    ขอนแก่น
Name: 11697, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] <= 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

1466
sex                      ชาย
age                       19
province_of_onset    ขอนแก่น
Name: 1466, dtype: object
9333
sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 9333, dtype: object
9334
sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object
10610
sex                      ชาย
age                       17
province_of_onset    ขอนแก่น
Name: 10610, dtype: object
11517
sex                      ชาย
age                       12
province_of_onset    ขอนแก่น
Name: 11517, dtype: object
11697
sex                     หญิง
age                       17
province_of_onset    ขอนแก่น
Name: 11697, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

       No.  ...                                               risk
6884  6885  ...                                  Cluster สมุทรสาคร
6885  6886  ...                                      Cluster ระยอง
6886  6887  ...                                        สถานบันเทิง
6887  6888  ...                                  Cluster สมุทรสาคร
6888  6889  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...

[5 rows x 10 columns]

In [ ]:
TF

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

### HW กลุ่ม 2 || เลือกข้อมูลมาเฉพาะวัน announce_date เป็นวันที่ 1-20

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.          age
count  12653.000000  8881.000000
mean    6327.000000    38.054748
std     3652.750813    15.125178
min        1.000000     0.100000
25%     3164.000000    27.000000
50%     6327.000000    36.000000
75%     9490.000000    48.000000
max    12653.000000    97.000000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

39.46076940331987

### ```.isnull()```

In [ ]:
data_covid.isnull()

         No.  announce_date  ...  district_of_onset   risk
0      False          False  ...               True  False
1      False          False  ...               True  False
2      False          False  ...              False  False
3      False          False  ...               True  False
4      False          False  ...               True  False
...      ...            ...  ...                ...    ...
12648  False          False  ...              False  False
12649  False          False  ...              False  False
12650  False          False  ...              False  False
12651  False          False  ...              False  False
12652  False          False  ...              False  False

[12653 rows x 10 columns]

# next

*   ต่อตารางแกน X แกน y
*   .groupby
*   save table